baseURL = 'https://blog.ewala.es'
languageCode = 'es'
title = 'Ewala IT Services Blog'
theme = 'paper'

publishDir = "docs"

[params]
ewalalogo = 'https://ewalait.github.io/blogewala/images/ewala_w.png'
ewalafavicon = '/images/favicon.png'
color = 'light'
ewalateam = '/images/logo-hacker.png'
youtube = 'https://www.youtube.com/channel/UCMcvwAIxQNsI8WloxR9r_gg'
linkedin = 'https://www.linkedin.com/company/e-wala-it-services'
defaultpostimage = '/images/ewala.png'
pageEwala = 'https://www.ewala.es/'
pageBlog = 'https://blog.ewala.es/'
ewalaBlogImg = '/images/hackerLogo.png'
ewalaSecurityWizards = '/images/ewala_sec_wiz.png'

[pagination]
disableAliases = false
pagerSize = 6
path = 'page'