baseURL = 'https://blog.ewala.es'
languageCode = 'en-us'
title = 'Ewala IT Services Blog'
theme = 'paper'
[params]
ewalalogo = 'https://ewalait.github.io/blogewala/images/ewala_w.png'
ewalafavicon = '/images/favicon.png'
color = 'light'
ewalateam = '/images/logo-hacker.png'
youtube = 'https://www.youtube.com/channel/UCMcvwAIxQNsI8WloxR9r_gg'
linkedin = 'https://www.linkedin.com/company/e-wala-it-services'
defaultpostimage = '/images/ewala.png'